config/routes.rb
BloggerClone::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :posts

  resources :users do
    resources :posts
  end

  root to: "posts#index"
end

app/models/post.rb
class Post < ActiveRecord::Base

  validates :header, presence: true
  validates :content, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
  validates :email, presence: true

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params
    if @post.save
      current_user.posts << @post
      flash[:notice] = "Your post has been saved."
      redirect_to posts_path
    else
      flash[:alert] = "Something went wrong. Please try to save your post again."
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update post_params
      flash[:notice] = "Your post has been changed."
      redirect_to post_path @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "Your post has been removed."
    redirect_to posts_path
  end

private
  def post_params
    params.require(:post).permit(:header, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  private
  def post_params
    params.require(:post).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BloggerClone</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <%= link_to "Lorem Blog", root_url,
           :class => "navbar-text navbar-left" %>
      <%= link_to "New Post", new_post_path,
           :class => "navbar-text navbar-left" %>
      <% if user_signed_in? %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete,
            :class => "navbar-text navbar-right" %>
        <%= link_to "Logged in as #{current_user.email}", edit_user_registration_path,
            :class => "navbar-text navbar-right" %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path,
            :class => "navbar-text navbar-right" %>
        <%= link_to "Login", new_user_session_path,
            :class => "navbar-text navbar-right" %>
      <% end %>
    </div>
  </div>
  <div class="container">
    <%= flash[:notice] %>
    <%= flash[:alert] %>
    <%= yield %>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= render("layouts/errors", :object => @post) %>

<%= form_for @post do |f| %>
  <div class="form-group">
    <div class="col-md-6">
      <%= f.text_field :header, class: "form-control", placeholder: "Header" %>
    </div>
  </div><br><br><br>

  <div class="form-group">
    <div class="col-md-9">
      <%= f.text_area :content, size: "15x15", class: "form-control", placeholder: "Your post here..." %>
    </div>
  </div><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

  <div class="submit">
    <%= f.submit(:class => "btn btn-primary") %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Lorem Blog</h1>

<ul>
  <% @posts.each do |post| %>
    <li><%= link_to post.header, user_post_path(post) %></li><br>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.header %></h1>

<p><h5>by: <%= @post.user.name %></h5></p>
<p><%= @post.content %></p>
<%= link_to "Edit", edit_post_path, :class => "btn btn-primary" %>
<%= link_to "Delete", post_path(@post),
                      data: { :confirm => "Sure you want to delete?" },
                      :method => "delete",
                      :class => "btn btn-danger" %>